version: '3.1'
services:
    jenkins:
      build: 
        context: .
        dockerfile: Dockerfile.jenkins
      container_name: jenkins
      ports:
        - '8080:8080'
        - '50000:50000'
    jenkins-worker:
      build: 
        context: .
        dockerfile: Dockerfile.jenkins-worker
      container_name: jenkins-worker
      restart: always
      environment:
        - 'JENKINS_URL=http://jenkins:8080'
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
        - /home/jenkins:/home/jenkins # Avoid mysql volume mount issue
      depends_on:
        - jenkins